### ISSUE TITLE
problem with the stack.sh script

### ISSUE THREAD

**Issue by crevillo** [kaliop/ezdocker-stack#1]
hi. i have a problem with the stack.sh. it doesn't reach the part where it should clone the url you enter. 
i think this is a bug in the script... shouldn't these conditions be `&&` instead of `||`? https://github.com/kaliop/ezdocker-stack/blob/master/stack.sh#L108 

Thank you.

**Comment by supasteev0** [comment]
Hi @crevillo .

There is indeed a bug in the shell script.

I will fix it soon, thank you for the report.

**Comment by supasteev0** [comment]
Fixed !
