### ISSUE TITLE
Consider adding Node.js to CLI container

### ISSUE THREAD

**Issue by fvsch** [kaliop/ezdocker-stack#13]
Use case: we have configuration files and scripts for Node.js tools committed in projects and used by front-end developers to compile CSS, SVG sprites, and more. Currently these tools are only used by front-end developers. We would like to enable other developers to use them reliably, especially (but not only) for devs from our Maintenance/Support team.

Could we maybe install Node.js in the CLI container?
Something like:

```
# Node.js - https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
RUN apt-get install -y nodejs
```

**Comment by ScreamZ** [comment]
+1

**Comment by punknroll** [comment]
+1

**Comment by supasteev0** [comment]
Done
