### ISSUE TITLE
cli french language

### ISSUE THREAD

**Issue by punknroll** [kaliop/ezdocker-stack#14]
Hi,

when I login to docker exec -ti cli su site the language is french. How can I change that? I think it should be english by default.

greetz

**Comment by supasteev0** [comment]
@punknroll : I have indeed set the system locale in all Docker images to fr_FR.UTF-8, as most of the developers in my company work on projects for french companies.

Unfortunately, the locale can only be set during image build, so you would have to edit the Dockerfile for the cli image and build it on your host to change the locale: 


`ARG DOCKER_LOCALE=eng_GB.UTF-8`

**Comment by punknroll** [comment]
Thank you for your answer. I forked your repo and made custom images with english locales.

**Comment by supasteev0** [comment]
Glad you could find a solution ;)
