### ISSUE TITLE
phpmemadmin not working for me

### ISSUE THREAD

**Issue by crevillo** [kaliop/ezdocker-stack#2]
hi again. i have almost everything running it seems. great work, btw :). 
The only thing i still don't have is phpmemadmin. 
I go to http://localhost:88 and see all those links. All of them work except the phpmemadmin. Clicking on it i get a error 500 saying 
`
PHP Fatal error:  require_once(): Failed opening required 'Clickalicious/PhpMemAdmin/Bootstrap.php' (include_path='.:/usr/share/php:/usr/share/pear:/home/site/controlpanel/phpmemadmin/') in /home/site/controlpanel/phpmemadmin/web/index.php on line 73, referer: http://localhost:88/
`

May it be that there's the need to execute a composer install inside that folder to get these dependencies? 

Cheers.

**Comment by supasteev0** [comment]
This issue should be solved with latest update. Can you please try again and close the issue if it's working for you ?

**Comment by crevillo** [comment]
Great!. Working now. Thanks again.
