### ISSUE TITLE
nginx logs not in gitignore

### ISSUE THREAD

**Issue by fvsch** [kaliop/ezdocker-stack#23]
After setup with the nginx option, the `logs/nginx` directory is created, but it's not included in `.gitignore` so its contents show up on `git status`.

I tried editing `.gitignore` and creating `logs/nginx/.gitkeep` for a PR, but it looks like Docker took over the permissions on this directory so I can't touch it.

**Comment by supasteev0** [comment]
@fvsch fixed in master
