### ISSUE TITLE
"No DOCKER_WEB_SERVER defined!" after aborted setup

### ISSUE THREAD

**Issue by fvsch** [kaliop/ezdocker-stack#24]
If the setup aborts after `buildDockerComposeConfigFileIfNeeded` (e.g. in `configurePhpVersion` or `configureWebServer`), then there will be a `docker-compose.config.sh` in the folder and users can get stuck when trying to restart the setup:

```
$ ./stack.sh start
No DOCKER_WEB_SERVER defined! Please run script with option web_server_switch
```

**Comment by supasteev0** [comment]
@fvsch As the error states: in this case you have to run the script with the web_server_switch option in order to finalize configuration. Not much much we can do for this.

**Comment by fvsch** [comment]
Why not call `configureWebServer` directly instead of telling users to call the corresponding option?

**Comment by supasteev0** [comment]
@fvsch fixed in master
