### ISSUE TITLE
Apache not starting in web container

### ISSUE THREAD

**Issue by crevillo** [kaliop/ezdocker-stack#3]
Hi there. I've just done a new clone and build. Everything ok. Problem is starting. looks apache of web container is not starting. entering the container and trying to manually start it i get this error

```
docker exec -ti web su site
root@crevillo_web:/var/www# /etc/init.d/apache2 start
Starting web server: apache2 failed!
The apache2 configtest failed. ... (warning).
Output of config test was:
AH00526: Syntax error on line 109 of /etc/apache2/apache2.conf:
Error:\tApache has not been designed to serve pages while\n\trunning as root.  There are known race conditions that\n\twill allow any local user to read any file on the system.\n\tIf you still desire to serve pages as root then\n\tadd -DBIG_SECURITY_HOLE to the CFLAGS env variable\n\tand then rebuild the server.\n\tIt is strongly suggested that you instead modify the User\n\tdirective in your httpd.conf file to list a non-root\n\tuser.\n
Action 'configtest' failed.
The Apache error log may have more information.
```

A question about... it's normal that when diong this looks i'm logged as root instead of site? 
Further more, if i do a `id site` in the container i'm getting
root@crevillo_web:/var/www# id site
uid=0(root) gid=0(root) grupos=0(root)

```

one thing to know if it helps... i did the build with root user... don't know if this is a problem... 
```

**Comment by supasteev0** [comment]
Hi, 

This is rather strange but it may indeed come from the fact that you run (the build process should not matter) the container with a root user. It is odd that you get a prompt with root user when executing the command su site ... 
The bootstrap process changed the id of the user with the currently logged in user id, which is why you get root with id u.
Can you try to run the stack with a user other than root, as it is highly not recommended to run Docker containers with a root user on the host ?

**Comment by crevillo** [comment]
hello, just did it, but again same issue. following doc i've tried to enter the web container with `su site`, but again it looks i'm entering as root there...

```
carlosrevillo@back04:~/docker/ezdocker-stack$ docker exec -ti web su site
root@crevillo_web:/var/www# whoami
root
root@crevillo_web:/var/www# id site
uid=0(root) gid=0(root) grupos=0(root)
```

**Comment by crevillo** [comment]
it's indeed quite strange... i was looking to the bootrap of the web image. one of the commands it tries is https://github.com/kaliop/ezdocker-stack/blob/master/images/web/bootstrap.sh#L35

But the thing is if i try to list that file, root looks again the owner...

```
root@crevillo_web:/var/www# ls -la /var/lock/apache2
total 8
drwxr-xr-x 2 root root 4096 may 25 12:28 .
drwxrwxrwt 4 root root 4096 may 25 15:17 ..
```

i'll try to remove everything and start again...

**Comment by crevillo** [comment]
imho there's something wrong in the bootstrap.sh part. here's what i found. i've added two scripts simulating what Dockerfile and bootstrap.sh do. First script

``` shell
addgroup --gid 1015 crevillo && \
    adduser --system --uid=1015 --gid=1015 \
        --home /home/crevillo --shell /bin/bash crevillo && \
    adduser crevillo crevillo && \
    adduser crevillo www-data && \
    mkdir -p /home/crevillo/.ssh; \
    cp /etc/skel/.* /home/crevillo/; \
    chown -R crevillo:crevillo /home/crevillo;
```

After executing this i try to get info of this new user and looks correct

``` shell
root@crevillo_web:/root# ./carlos.sh 
Añadiendo el grupo `crevillo' (GID 1015) ...
Hecho.
Añadiendo el usuario del sistema `crevillo' (UID 1015) ...
Añadiendo un nuevo usuario `crevillo' (UID 1015) con grupo `crevillo' ...
Creando el directorio personal `/home/crevillo' ...
Añadiendo al usuario `crevillo' al grupo `crevillo' ...
Añadiendo al usuario crevillo al grupo crevillo
Hecho.
Añadiendo al usuario `crevillo' al grupo `www-data' ...
Añadiendo al usuario crevillo al grupo www-data
Hecho.
cp: se omite el directorio «/etc/skel/.»
cp: se omite el directorio «/etc/skel/..»
root@crevillo_web:/root# id crevillo
uid=1015(crevillo) gid=1015(crevillo) grupos=1015(crevillo),33(www-data)
```

Now the second script. It has this code (taken from bootstrap.sh)

```
ORIGPASSWD=$(cat /etc/passwd | grep crevillo)
ORIG_UID=$(echo $ORIGPASSWD | cut -f3 -d:)
ORIG_GID=$(echo $ORIGPASSWD | cut -f4 -d:)
ORIG_HOME=$(echo "$ORIGPASSWD" | cut -f6 -d:)
DEV_UID=${DEV_UID:=$ORIG_UID}
DEV_GID=${DEV_GID:=$ORIG_GID}

if [ "$DEV_UID" -ne "$ORIG_UID" ] || [ "$DEV_GID" -ne "$ORIG_GID" ]; then

    # note: we allow non-unique user and group ids...
    groupmod -o -g "$DEV_GID" crevillo
    usermod -o -u "$DEV_UID" -g "$DEV_GID" crevillo

    chown "${DEV_UID}":"${DEV_GID}" "${ORIG_HOME}"
    chown -R "${DEV_UID}":"${DEV_GID}" "${ORIG_HOME}"/.*

fi
```

I execute it and then again i try `id crevillo`

``` shell
root@crevillo_web:/root# id crevillo
uid=0(root) gid=0(root) grupos=0(root)
```

it looks the created user gets "promoted" to root somehow...

**Comment by crevillo** [comment]
maybe is just my fault. looks like these two lines

```
DEV_UID=${DEV_UID:=$ORIG_UID}
DEV_GID=${DEV_GID:=$ORIG_GID}
```

sets DEV_UID and DEV_GID to 0 and hence, groupdmod and usermod commands executed later converts the user in root.

**Comment by supasteev0** [comment]
Yes, the variables should be set in your docker-compose.env.local file with your host current user & group ids. Maybe try to delete the docker-compose.config.sh &  docker-compose.env.local files & start the script again with a regular user

**Comment by crevillo** [comment]
This indeed was the issue and it's working now following remove docker-compose.config suggestiond and rebuilding again. 
Thanks a lot for your time.
