### ISSUE TITLE
config/web/php5/timezone.ini: No such file or directory

### ISSUE THREAD

**Issue by fvsch** [kaliop/ezdocker-stack#4]
Running `stack.sh` in Bash on Windows (living on the edge):

> ./stack.sh: line 138: config/web/php5/timezone.ini: No such file or directory

Indeed that file doesn't exist. There is a `config/cli/php5/timezone.ini`, and no `timezone.ini` in `config/apache/php5`.

Seen on latest master (826659de79ceb9e921161dc3098625a3dcb70551).

**Comment by supasteev0** [comment]
Fixed in latest stack.sh
