### ISSUE TITLE
Should volumes to the user’s host config be marked as read only (:ro)?

### ISSUE THREAD

**Issue by fvsch** [kaliop/ezdocker-stack#6]
I’m thinking about the volumes pointing to local user config, e.g.

```
  volumes:
    - ~/.gitconfig:/home/site/.gitconfig
    - ~/.ssh/config:/home/site/.ssh/config
```

is there a need for those to be writeable? or should they be marked as read-only?

```
  volumes:
    - ~/.gitconfig:/home/site/.gitconfig:ro
    - ~/.ssh/config:/home/site/.ssh/config:ro
```

**Comment by supasteev0** [comment]
@fvsch :  these volumes could be read only as you would normally edit them on hosts rather than inside containers

**Comment by fvsch** [comment]
Closing this issue, as I can see use cases where read-only config volumes could create issues (e.g. when needing to tweak git config). So it’s perhaps not a great default.
