### ISSUE TITLE
Windows + Git Bash: issues with ssh forwarding

### ISSUE THREAD

**Issue by fvsch** [kaliop/ezdocker-stack#7]
Running a ssh-agent inside Git Bash on Windows seems to work alright. I'm using this script to make sure I have a ssh-gent inside each Bash session, and to reuse the same agent if it's already running:
https://help.github.com/articles/working-with-ssh-key-passphrases/#auto-launching-ssh-agent-on-msysgit

I also enabled SSH agent forwarding, and verified on an unrelated SSH server that it does work.

But after (re)starting the stack and logging into the `cli` container, the agent forwarding is not working:

```
site@project_cli:~$ echo $SSH_AUTH_SOCK
/ssh-agent

site@project_cli:~$ cat /ssh-agent
!<socket >50523 s D26E7C74-CE61963F-EB71618D-8A8D3C12

site@project_cli:~$ ssh-add -L
Could not open a connection to your authentication agent.

site@project_cli:~$ echo $SSH_AUTH_PID


site@project_cli:~$ ssh-agent -a /ssh-agent
bind: Address already in use
unix_listener: cannot bind to path: /ssh-agent
```

It seems that there is no running ssh-agent. And running `ssh-agent -a /ssh-agent` doesn't seem to work either. So far, no luck.

For the record, my current hackish solution is to mount `~/.ssh` in read-only mode:

```
  cli:
    volumes:
      - ~/.ssh:/home/site/ssh:ro
```

Not pretty, but it works.

**Comment by supasteev0** [comment]
I guess this work-around should stay in docker-compose.yml file only and not in template file as it is indeed very ugly ;)
