### ISSUE TITLE
Too many symbolink links

### ISSUE THREAD

**Issue by Tyki** [kaliop/ezdocker-stack#8]
Hi,

When mounting /mnt/<username> containing whole workspace and potential internal symbolic links, there is an issue acceding to /mnt/<username>/workspace from inside the docker. The error is the following one : 

bash: cd: /mnt/<username>/workspace/: Trop de niveaux de liens

**Comment by supasteev0** [comment]
This is actually a Linux issue related to the path mounted as volume containing too many circular symbolic links, and not a Docker issue . The only way to fix it is to restart the stack or mount another path containing less symbolic links.
