### ISSUE TITLE
jpegoptim

### ISSUE THREAD

**Issue by vfaisse** [kaliop/ezdocker-stack#9]
Installer jpegoptim sur le container CLI et Web.

**Comment by supasteev0** [comment]
Question : why is it needed in cli container ? As only the web container should need it to generate image aliases.

**Comment by vfaisse** [comment]
You can have to need to optimize existing pictures or test settings of optimization in command line.

**Comment by supasteev0** [comment]
@Petitmur : jpegotpim has been added to all cli & web images
